export const USER_REPOSITORY = 'USER_REPOSITORY';

export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';

export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';

export const USER_LOGIN_HISTORY_REPOSITORY = 'USER_LOGIN_HISTORY_REPOSITORY';

export const LESSON_REPOSITORY = 'LESSON_REPOSITORY';
